#!/bin/bash
# Script fuer inkrementelles Backup mittels rsync

### Einstellungen ##
BACKUPDIR="/mnt/SSD/Backup_Weekly/"        ## Pfad zum woechentlichen Backupverzeichnis
BACKUPOLDDIR="/mnt/SSD/Backup_Monthly/" ## Pfad zum monatlichen Backupverzeichnis
DATUM="$(date +%d-%m-%Y)"          	 	   ## Datumsformat einstellen
ZEIT="$(date +%H:%M)"              		   ## Zeitformat einstellen

### Verzeichnisse/Dateien welche nicht gesichert werden sollen ! Achtung keinen Zeilenumbruch ! ##
EXCLUDE= --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"}

### Wechsel in root damit die Pfade stimmen ##
cd /

### Backupverzeichnisse anlegen ##
mkdir -p ${BACKUPDIR}
mkdir -p ${BACKUPOLDDIR}

### Test ob Backupverzeichnis existiert und Mail an Admin bei fehlschlagen ##
if [ ! -d "${BACKUPDIR}" && "${BACKUPOLDDIR}" ]; then

mail -s "Backupverzeichnisse nicht vorhanden!" root <<EOM
Hallo Admin,
das Backup am ${DATUM} konnte nicht erstellt werden. Das Verzeichnis ${BACKUPDIR} wurde nicht gefunden und konnte auch nicht angelegt werden.
Mit freundlichem Gruss Backupscript
EOM

 . exit 1
fi

### Nutzer auf Backupprozess hinweisen ##

clear
echo "Woechentliches Backup wird ausgefuehrt. Diesen Vorgang bitte nicht abbrechen!"
sleep 10

### Nun wird das eigentliche Backup ausgefuehrt ##
rsync -aAXv --delete ${EXCLUDE} / ${BACKUPDIR}


### Abfragen ob das Backup erfolgreich war ##
if [ $? -ne 0 ]; then

mail -s "Backup (${DATUM}) war fehlerhaft!" root <<EOM
Hallo Admin,
das Backup am ${DATUM} wurde mit Fehler(n) beendet.
Mit freundlichem Gruss Backupscript
EOM

else

mail -s "Backup (${DATUM}) war erfolgreich" root <<EOM
Hallo Admin,
das Backup am ${DATUM} wurde erfolgreich beendet.
Mit freundlichem Gruss Backupscript
EOM

fi

### Update Pakete ###

sudo apt-get update

### Alte Installationspakete löschen

sudo apt-get clean

### Abfrage ob Upgrade durchgeführt werden soll mit Auflistung der Pakete ###

sudo apt-get -u upgrade

echo "Woechentliches Backup erfolgreich abgeschlossen."

exit 0
